### ISSUE TITLE
Problem while running second analysis from gui_app.py - Analysis doesn't run

### ISSUE THREAD

**Issue by nieiwona** [JPoziemski/DRAW#54]
May be a problem with GUI, the analysis doesn't start after generating new config and clicking run, then there is a need to load existing config and analysis starts. BEFORE ADDING LOAD CONFIG FUNCTIONALITY IT WORKED FINE. @przemekiljan analyze processes generate and load config, are they splitted, do both run analysis?

When analysis starts it shows:
172.17.0.1 - - [16/Jun/2020 16:04:45] "GET /run_from_config HTTP/1.1" 200 -

When doesn't run it stops at:
172.17.0.1 - - [16/Jun/2020 16:04:43] "GET /overview?tool_INITIAL_QUALITY_CONTROL=FastQC_0&FastQC_0_param%21--min_length=&FastQC_0_param%21--kmers=&tool_TRIMMING=TRIMMOMATIC&TRIMMOMATIC_param%21ILLUMINACLIP=&TRIMMOMATIC_param%21SLIDINGWINDOW=4%3A15&TRIMMOMATIC_param%21MAXINFO=&TRIMMOMATIC_param%21LEADING=1&TRIMMOMATIC_param%21TRAILING=1&TRIMMOMATIC_param%21CROP=&TRIMMOMATIC_param%21HEADCROP=&TRIMMOMATIC_param%21MINLEN=20&TRIMMOMATIC_param%21AVGQUAL=&tool_AFTER_TRIMMING_CONTROL=FastQC_1&FastQC_1_param%21--min_length=&FastQC_1_param%21--kmers=&tool_MAPPING=Bowtie2&hisat_param%21--mp=&Hisat2_param%21--sp=&Hisat2_param%21--np=&Hisat2_param%21--rdg=&Hisat2_param%21--rfg=&Hisat2_param%21--seed=&Bowtie2_param%21--N=&Bowtie2_param%21--L=&Bowtie2_param%21--dpad=&Bowtie2_param%21--gbar=&Bowtie2_param%21--mp=&Bowtie2_param%21--np=&Bowtie2_param%21--rdg=&Bowtie2_param%21--rfg=&tool_COUNTING=Stringtie&Stringtie_param%21--l=&Stringtie_param%21--f=&Stringtie_param%21--m=&Stringtie_param%21--a=&Stringtie_param%21--c=&Stringtie_param%21--s=&Stringtie_param%21--g=&Stringtie_param%21--M= HTTP/1.1" 200 -

**Comment by przemekiljan** [comment]
Apparently loading site from static prevents it from loading python script anew. Fixed it by using flask.render_template instead of app.send_static_file. It should be fine now, let me know if this bug reappear
